### ISSUE TITLE
textract output - layout recognition

### ISSUE THREAD

**Issue by celw10** [Bmitch44/textract-demo#1]
Awesome progress. 

Perhaps a next logical step would be to detect features in the layout, like text, tables, headers, ect. Something like the attached. 

Also, are you aware of any image processing "under the hood" of textract? 

![layout](https://github.com/Bmitch44/textract-demo/assets/34209214/48294fa9-8971-43d2-b6bc-82c77e523440)

**Comment by Bmitch44** [comment]
I'm currently working on creating a parser which will sort through the data and try to map out relationships between blocks, there is a Python package called amazon-textract-parser that does this, but this won't work for our semi-structured data. I will create something like it where I will make classes to represent different blocks returned by Textract, making it easier to make sense of the data. Then I should be able to start actually mapping out parts of the pdf like in the image above.

I also am going to look into some pre-processing methods before I put the pdf through Textract, this should help get better results from Textract because right now, there are only lines being recognized and no tables or other elements are getting recognized.

I haven't had a look at what goes on under the hood of Textract yet, but I plan to do this as I get deeper into the project and try to optimize some things.

**Comment by Bmitch44** [comment]
![output2_bb ](https://github.com/Bmitch44/textract-demo/assets/87099534/d825ca55-c227-435a-9bfb-0b238fdaf781)


have drawn bounding boxes and labelled them with their BlockType from the Textract results. I used the Textract Response Parser (trp) with a few modifications to parse the JSON file and locate the lines, tables, checkboxes, and key-value sets in the document.

This method worked successfully with the [test2.pdf](https://github.com/Bmitch44/textract-demo/files/11630701/test2.pdf) file, but not as well with [test.pdf](https://github.com/Bmitch44/textract-demo/files/11630703/test.pdf). This difference in results is expected as the second file is much cleaner. However, I did achieve success in deskewing the test.pdf file and then running it through Textract. This can be seen when comparing [output_bb.pdf](https://github.com/Bmitch44/textract-demo/files/11630705/output_bb.pdf) with [output_deskewed_bb.pdf](https://github.com/Bmitch44/textract-demo/files/11630704/output_deskewed_bb.pdf). It's evident that the second result captures more of the document.

Moving forward, I plan to delve deeper into the preprocessing aspect of this project once I can consistently achieve good results from high-quality test files.
